config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources 'inventory_items'
  resources 'invoice_items'
  resources 'invoices'
  resources 'categories'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :inventory_items
  validates_presence_of :name

  def self.most_popular_for_invoice(invoice_id)
    Category
      .select('categories.name, invoice_items.quantity * COUNT(categories.name) AS total')
      .joins(inventory_items: [:invoice_items])
      .where(invoice_items: { invoice_id: invoice_id })
      .group(:name)
      .order('total DESC')
      .limit(1)
      .first
      .try(:name)
  end
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  has_many :invoice_items, dependent: :destroy
  belongs_to :category
  validates_presence_of :description
  validates_associated :invoice_items

  def quantity
    @quantity = invoice_items.sum(&:quantity)
  end

  def category_name
    category.try(:name)
  end

  def category_name=(name)
    self.category = Category.find_or_create_by!(name: name) if name.present?
  end

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :supplier
  has_many :invoice_items, dependent: :destroy, inverse_of: :invoice
  accepts_nested_attributes_for :invoice_items, reject_if: :all_blank, allow_destroy: true
  validates_associated :invoice_items

  def total
    @total = invoice_items.sum(&:calculated_total)
  end

  def supplier
    @supplier = Supplier.find(supplier_id)
  end

  def category
    Category.most_popular_for_invoice(id).capitalize
  end

  # Itemised Expenditures.
  # ie. Year-To-Date spend on a particular InventoryItem

  # Possible separation gotcha! with calculating Profit of a product.
  # Inventory Item needs to somehow link back to an invoice_item
  #
  # Product.new( cost: 12, quantity: 11, invoice_item: InvoiceItem[0] )
  #
  # When creating a product, assign the earliest available inventory_item


end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :inventory_item
  validates_presence_of :quantity, :cost, :inventory_item
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cost, numericality: true
  accepts_nested_attributes_for :inventory_item, reject_if: :all_blank, allow_destroy: true

  def calculated_total
    cost * quantity
  end

  def inventory_item_description
    InventoryItem.try(:description)
  end

  def inventory_item_description=(name)
    self.inventory_item = InventoryItem.find_or_create_by!(description: description) if description.present?
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :invoices

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:name).where('name like ?', "%#{params[:term]}%")
    render json: @categories.map(&:name)
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]

  def index
    @inventory_items = InventoryItem.order(:description).where('description like ?',"%#{params[:term]}%")
    render json: @inventory_items.map(&:description)
  end

  def new
    @inventory_item = InventoryItem.new
  end

  def create
    @inventory_item = InventoryItem.new(inventory_item_params)
    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to @inventory_item, notice: 'Inventory Item was successfully created'}
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: 'Inventory Item was successfully destroyed.'}
    end
  end

  private

  def set_inventory_item
    @inventory_item = InventoryItem.find(params[:id])
  end

  def inventory_item_params
    params.require(:inventory_item).permit(:description, :quantity, :category_id, :_destroy, :id)
  end
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  before_action :set_invoice_item, only: [:show, :edit, :update, :destroy]

  def index
    @invoice_items = InvoiceItem.all
  end

  def new
    @invoice_item = InvoiceItem.new
  end

  def create
    @invoice_item = InvoiceItem.new(invoice_item_params)
    respond_to do |format|
      if @invoice_item.save!
        format.html { redirect_to @invoice_item, notice: 'Invoice Item was successfully created' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @invoice_item.destroy
    respond_to do |format|
      format.html { redirect_to invoice_items_url, notice: 'Invoice Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_invoice_item
    @invoice_item = InvoiceItem.find(params[:id])
  end

  def invoice_item_params
    params.require(:invoice_item).permit(:cost, :quantity, :invoice_id, :inventory_item_id, inventory_item_attributes: [:description, :quantity, :_destroy, :id, :category_id])
  end
end

app/controllers/invoices_controller.rb
require 'features/invoice_params'

class InvoicesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_invoice, only: [:show, :edit, :destroy, :update]

  def index
    params[:sort] ||= 'id'
    @invoices = Invoice.order(sort_column + " " + sort_direction)
  end

  def new
    @invoice = Invoice.new
    @invoice.invoice_items.build
  end

  def edit
  end

  def create
    @invoice = InvoiceParams.call(invoice_params)
    respond_to do |format|
      if @invoice.save!
        format.html { redirect_to @invoice, notice: 'You have successfully created an invoice!'}
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
    end
  end

  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:invoice_number, :received_on_date, :supplier_id, :invoice_item_id, invoice_items_attributes: [:cost, :quantity, :_destroy, :invoice_id, :inventory_item_id, inventory_item_attributes: [:description, :_destroy, :id, :category_id, :category_name]])
  end

  def sort_column
    params[:sort] || 'id'
  end

  def sort_direction
    params[:direction] || 'asc'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, sort: column, direction: direction
  end
end

app/views/application/index.haml
.front__page.flex.column
  %h1.title
    Marchant
    %span &
    Co
  .card__row.flex.row
    - options = ['invoices']
    - options.each do |option|
      .card.box-shadow.flex.column
        = image_tag("icons/#{option}.png", class: 'icon--large card__image')
        .card__link__container.flex
          = link_to "#{option}", class: 'card__link' do
            = option.capitalize
          = link_to '+', {:controller => option, :action => :new}, {:class=>'button--circular--large inverse card__button text--bold'}

app/views/inventory_items/index.haml
%table.table
  %thead.table__header
    %th.table__header__text Id
    %th.table__header__text Description
    %th.table__header__text Quantity
  %tbody.table__body
    - @inventory_items.each do |inventory_item|
      %tr.table__row
        %td.table__cell= inventory_item.id
        %td.table__cell= inventory_item.description
        %td.table__cell= inventory_item.quantity
        %td.table__cell= link_to 'Delete', inventory_item, method: :delete, data: { confirm: 'Are you sure you want to delete this?' }
= link_to 'New', new_inventory_item_path

app/views/inventory_items/new.haml
= form_for @inventory_item do |f|
  .fieldset
    = f.label :description
    = f.text_field :description
  = f.submit

app/views/invoice_items/index.haml
= link_to 'New Invoice Item', new_invoice_item_path, class: 'button align-right'
%table.table
  %thead.table__header
    %th.table__header__text Id
    %th.table__header__text Quantity
    %th.table__header__text Cost
    %th.table__header__text Inventory Item
    %th.table__header__text
  %tbody
    - @invoice_items.each do |invoice_item|
      %tr.table__row
        %td.table__cell= invoice_item.id
        %td.table__cell= invoice_item.quantity
        %td.table__cell= invoice_item.cost
        %td.table__cell= invoice_item.inventory_item.description
        %td.table__cell= link_to 'Delete', invoice_item, method: :delete, data: { confirm: 'Are you sure you want to delete this?' }

app/views/invoice_items/new.haml
= simple_form_for @invoice_item do |f|
  .fieldset
    = f.label :quantity
    = f.text_field :quantity
  .fieldset
    = f.label :cost
    = f.text_field :cost
  .fieldset
    = f.input :inventory_item_id, collection: InventoryItem.all if InventoryItem.any?
    %p Add New Inventory Item
    = f.simple_fields_for :inventory_item, InventoryItem.new do |inventory_item|
      = inventory_item.input :description
  .fieldset
    = f.input :invoice_id, collection: Invoice.all
  = f.submit

app/views/invoice_items/show.haml
%table
  %thead
    %th Description
    %th Quantity
    %th Cost
  %tbody
    %tr
      %td= link_to @invoice_item.inventory_item.description, @invoice_item.inventory_item
      %td= @invoice_item.quantity
      %td= @invoice_item.cost

app/views/invoices/_display.haml
%table.table
  %thead.table__header
    %th.table__header__text Description
    %th.table__header__text Category
    %th.table__header__text Quantity
    %th.table__header__text Unit Price
    %th.table__header__text Total
  %tbody
    - @invoice.invoice_items.each do |item|
      %tr.table__row
        %td.table__cell= item.inventory_item.description
        %td.table__cell= item.inventory_item.category.name
        %td.table__cell= item.quantity
        %td.table__cell= number_to_currency item.cost
        %td.table__cell= number_to_currency item.calculated_total

app/views/invoices/_form.haml
= simple_form_for @invoice, :data => {:persist => 'garlic'},:html => {:class => 'form'} do |f|
  .box-shadow
    .form__header
      = f.input :invoice_number, label_html: {class: 'form__header__label'}, label: 'Invoice #'
      = f.input :received_on_date, label_html: {class: 'form__header__label'}, order: [:day, :month, :year]
      = f.input :supplier_id, collection: Supplier.all, include_blank: false, label_html: {class: 'form__header__label'}
      %h1.form__header__title
        = action_name.capitalize
        %span
          = controller_name.singularize.capitalize
    .existing_data
    = render 'display' unless params[:action] == 'new'
    %table.table
      - unless params[:action] == 'edit'
        %thead.table__header
          %th.table__header__text Description
          %th.table__header__text Category
          %th.table__header__text Quantity
          %th.table__header__text Cost
          %th.table__header__text Delete?
      %tbody
        = f.simple_fields_for :invoice_items, InvoiceItem.new do |invoice_item|
          = render partial: 'invoice_item_fields', locals: { f: invoice_item }
  .form__footer
    = link_to_add_association 'Add Item', f, :invoice_items, data: {"association-insertion-node" => "tbody", "association-insertion-method" => "append"}, class: 'form__footer__link'
  = f.submit 'Create Invoice', data: { confirm: 'Finished adding items and would like to submit?' }, class: 'button align-right'

app/views/invoices/_invoice_item_fields.haml
%tr.nested-fields.table__row
  = f.simple_fields_for :inventory_item, InventoryItem.new do |inventory_item|
    %td= inventory_item.text_field :description, data: { autocomplete_source: inventory_items_path }, placeholder: 'Description'
    %td= inventory_item.text_field :category_name, data: { autocomplete_source: categories_path }, placeholder: 'Category'
  %td= f.input :quantity, label: false, placeholder: 'Quantity', input_html: {min: 0, step: 1}
  %td= f.input :cost, label: false, placeholder: 'Cost', input_html: {min:0, step: 'any'}
  %td
    = link_to_remove_association "Remove", f, data: { confirm: 'Are you sure?'}

app/views/invoices/edit.haml
= render 'form'

app/views/invoices/index.haml
%h1.heading Invoices
.options
  = link_to '+', new_invoice_path ,class: 'button--circular icon align-right'
  = image_tag('icons/settings.png', class: 'icon settings')
%table.table.box-shadow
  %thead.table__header
    %th.table__header__text= sortable('invoice_number', 'Invoice #')
    %th.table__header__text= sortable 'supplier_id'
    %th.table__header__text Category
    %th.table__header__text= sortable 'received_on_date', 'Received On'
    %th.table__header__text Total
    %th.table__header__text.settings_options
      Options
  %tbody.table__body
    - @invoices.each do |invoice|
      %tr.table__row.clickable-row{"data-href" => invoice_url(invoice) }
        %td.table__cell= invoice.invoice_number
        %td.table__cell= invoice.supplier.name
        %td.table__cell= invoice.category
        %td.table__cell.text--bold= invoice.received_on_date.strftime('%a, %d %b %Y')
        %td.table__cell= number_to_currency invoice.total
        %td.table__cell.settings_options
          = link_to edit_invoice_path(invoice), class: 'settings_options__link' do
            = inline_svg('icons/edit.svg', class: 'icon--s edit', data: {:title => 'Edit'})
          = link_to invoice, :method => :delete, data: {confirm: 'Are you sure?'}, class: 'settings_options__link' do
            = inline_svg('icons/delete.svg', class: 'icon--s delete', data: {:title =>'Delete'})

app/views/invoices/new.haml
= render 'form'

app/views/invoices/show.haml
.show.box-shadow
  .form__header
    %h1.heading
      Invoice #
      %span= @invoice.invoice_number
    %ul
      %li
        %p.form__header__label Supplier
        %p.form__header__data= @invoice.supplier.name
      %li
        %p.form__header__label Received on
        %p.form__header__data= @invoice.received_on_date
      %li
    .price__container
      %h1.price__container__label Total:
      %p.price__container__data= number_to_currency @invoice.total
  = render 'display'
  .form__footer
    = link_to 'Edit Invoice', edit_invoice_path, class: 'form__footer__link spanner'

app/views/layouts/_navigation.haml
%ul.nav
  = link_to root_path, class: 'nav__item' do
    = image_tag('icons/home.png', class: 'icon')
  %li.nav__item
    = image_tag('icons/invoices.png', class: 'icon')
    = link_to 'Invoices', invoices_path, class: 'nav__link'
    = link_to '+', new_invoice_path, class: 'button--circular'
  %li.nav__item
    = image_tag('icons/products.png', class: 'icon')
    = link_to 'Invoice_items', invoice_items_path, class: 'nav__link'
    = link_to '+', new_invoice_path, class: 'button--circular'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppV20</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Barlow:300,400,600|Exo+2|Shadows+Into+Light" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': false %>
</head>

<body>
<%= inline_svg('icons/training_wheels.svg', class: 'training_wheels_button') %>
<% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<%= render 'layouts/navigation' %>
<main class="flex column">
  <%= yield %>
</main>
</body>
</html>